# Generated by Django 5.0 on 2025-10-02 11:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(editable=False, help_text='Auto-generated patient ID', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone_number', models.CharField(help_text='Format: +254700000000', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+254700000000'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('insurance_provider', models.CharField(choices=[('NHIF', 'NHIF'), ('AAR', 'AAR Insurance'), ('BRITAM', 'Britam'), ('JUBILEE', 'Jubilee Insurance'), ('MADISON', 'Madison Insurance'), ('OTHER', 'Other'), ('NONE', 'No Insurance')], default='NONE', max_length=20)),
                ('insurance_number', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+254700000000'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('allergies', models.TextField(blank=True, help_text='List of known allergies', null=True)),
                ('chronic_conditions', models.TextField(blank=True, help_text='List of chronic conditions', null=True)),
                ('current_medications', models.TextField(blank=True, help_text='List of current medications', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DECEASED', 'Deceased')], default='ACTIVE', max_length=10)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_visit_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient_id'], name='patients_pa_patient_927c52_idx'), models.Index(fields=['first_name', 'last_name'], name='patients_pa_first_n_a142c0_idx'), models.Index(fields=['phone_number'], name='patients_pa_phone_n_933975_idx'), models.Index(fields=['status'], name='patients_pa_status_ca3fc5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('WALKIN', 'Walk-in'), ('APPOINTMENT', 'Scheduled Appointment'), ('EMERGENCY', 'Emergency'), ('FOLLOWUP', 'Follow-up')], max_length=20)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('reason_for_visit', models.TextField()),
                ('doctor_assigned', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('checked_in', models.BooleanField(default=False)),
                ('triage_completed', models.BooleanField(default=False)),
                ('consultation_completed', models.BooleanField(default=False)),
                ('lab_completed', models.BooleanField(default=False)),
                ('pharmacy_completed', models.BooleanField(default=False)),
                ('billing_completed', models.BooleanField(default=False)),
                ('visit_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField()),
                ('prescription', models.TextField(blank=True, null=True)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='patients.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.visit')),
            ],
            options={
                'verbose_name_plural': 'Medical histories',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['patient', '-visit_date'], name='patients_vi_patient_494a7c_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['visit_type'], name='patients_vi_visit_t_d647ed_idx'),
        ),
    ]
